name: Bot

on:
  workflow_dispatch:

jobs:
  RunBot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: SetUp Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.9

      - name: SetUp Dependences
        run: |
            python3 -m pip install -r requirements.txt

      - name: Execute bot.py
        run: |
            python bot.py
